image: toliak/latex:20201112

variables:
    NODE_ENV: production

prettier:
    before_script:
        - apt-get update -y --allow-releaseinfo-change
        - apt-get install -y npm nodejs
        - npm ci

    script:
        - npm run prettier

pdf:
    before_script:
        - apt-get update -y --allow-releaseinfo-change
        - apt-get install -y npm nodejs
        - npm ci

    script:
        - npm run build

    after_script:
        - cd out
        - mv main.pdf ../main.pdf

    artifacts:
        paths:
            - '*.pdf'
