image: toliak/latex:20201112

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 0

pdf:
  before_script:
    - cp -rf fonts/* /usr/local/share/fonts/
    - fc-cache -f -v
    - apt-get update -y --allow-releaseinfo-change
    - apt-get install -y python3 python3-pip
    - pip3 install -r python/md_to_latex/requirements.txt

  script:
    - sed -i "s/. .\/venv\/bin\/activate//g" "build.sh"
    - ./build.sh
    - ./build.sh
    - cd out
    - mv main.pdf ../`cat ../latex/codegen/output_name.txt`

  artifacts:
    paths:
      - "*.pdf"
