image: toliak/latex:minimal

prettier:
    script:
        - npm ci
        - npm run prettier

pdf:
    script:
        - npm install
        - npm run build

    after_script:
        - cd out
        - mv main.pdf ../main.pdf

    artifacts:
        paths:
            - '*.pdf'
